### ISSUE TITLE
how to get started?

### ISSUE THREAD

**Issue by robotamer** [marcelnicolay/torneira#1]
I like the principle but I can't get it going.
I have to admit that I am relatively new to python, can you write a short howto get started?

I created a settings-local.py file with following content:

DEBUG = True
PROFILING = False
COOKIE_SECRET = "29NbhyfgaA092ZkjMbNvCx06789jdA8iIlLqz7d1D9c8"

I am looking for something like following but can't find it. Also where would i set the host, port, etc.

if **name** == "**main**":
    daemon = Torneira('/tmp/tornado.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)

**Comment by marcelnicolay** [comment]
Now, you can use the torneira script. Install the latest version of torneira, go to your app directory and make:

$ torneira start

Torneira will be started at http://localhost:8080

I'm work in documentation and a demo application, to help people understand the idea of torneira.
There is already an application for demonstration, https://github.com/marcelnicolay/torneira/tree/master/demo
